sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IvQmC3p481Z3sq52QWQVY0/9Retyw6MSms8VxspTFDOZ+BnWSxJcgyLznTOWPRb1AboLf8PMhMrHkqxp9SOZ1wKQuDx2+dDQWoBGxH3TzinGFLr4WoNVe22jbX6HAjhxmQpa8jE4oIHxWHpmuyi7Vq7bGHPzx5rSqRg80ikLhXNqH7Wq4IxZP7Oi3kWPz79Uq8Kx3B9Ylynch9+YwTx75NUHgcbTXGrvUZeAGux6f8pp3EI/hPkYIA58cBKt4izoCEDeKr7EYsE30Wm9CMBE0AOsoHVGOmpJcNazdgtlBv5df9xot8aebZefUSX1G6L9Jiz2PXlKX6qiTO2hjJyzAYmxnKer95YMnH+ZkFjw0wyXmUTrbGWTAfNOo8cr5dEkSRH9OgSUBMwqciqgp/u5rtt1EnABb+WjpV/BY/LFpS3+50BWiMHB7GVevgrD66+zuuZEelfQ//QLnbUCjP0Zr4X5zLipr5RWsCYjJoGq9CtHvP+8AV32b+C7C9GOt0WZywoEf++lPSC1hADVvgY+U0CS3hhBkBykexHzu+Of9ElDko4gFjKRsaU+GrLkJMJGol93ZXXsX0kFYCA0QI5DSkHf2CEFaPCZaaSNNUOOcKl6ViJUw7dgWuDOOZtiVQxsojN34jBfMFEfi8o24Kccv563N4YzLE68AEYj8hfsIy0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Barry-Lyndon_4558
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy